In [ ]:
import sys
sys.path.append('/home/pulpo/Documents/quantitative-trading')
from src.quanttrading.analysis import calculate_stats, detect_outliers
from src.quanttrading.data import prepare_data
import pandas as pd

In [10]:
# DOWNLOAD DATA
df_nvda = prepare_data('NVDA', '6mo', '4h')

print('\nPrimeras filas')
df_nvda.head()

[*********************100%***********************]  1 of 1 completed

Primeras filas

Price,Close,High,Low,Open,Volume,Return
Datetime,,,,,,
2025-10-30 17:30:00+00:00,202.800003,204.479904,201.880005,203.059998,30835291,-0.125577
2025-10-31 13:30:00+00:00,202.836502,207.970001,202.070007,206.449997,66218777,0.017998
2025-10-31 17:30:00+00:00,202.399994,204.770004,202.389999,202.809998,30885876,-0.215202
2025-11-03 14:30:00+00:00,210.959900,211.335007,206.800003,208.054993,76212335,4.229203
2025-11-03 18:30:00+00:00,207.020004,211.050003,206.330002,210.955002,43104336,-1.867604

In [ ]:
print('\nRETURN STATISTICS\n')

stats = calculate_stats(df_nvda['Return'])
for key, value in stats.items():
    print(f'{key}: {value: .4f}')

print('\nDetecting outliers\n')

outliers = detect_outliers(df_nvda['Return'], thereshold=3)

print(f'Total de dias:     {len(df_nvda)}')
print(f'Dias con outliers: {outliers.sum()}')
print(f'Porcentaje:       {(outliers.sum() / len(df_nvda) * 100): .2f}%')

print('\nDias con outliers (mostrando Return y distancia de STD):\n')
outlier_days = df_nvda[outliers][['Return']].copy()
outlier_days['Distance_from_mean (STD)'] = ((df_nvda['Return'] - stats['mean']).abs() / stats['std'])[outliers]
outlier_days

RETURN STATISTICS

mean:  0.0255
std:  1.6180
skew:  0.3144
kurt:  2.4077

Detecting outliers

Total de dias:     243
Dias con outliers: 3
Porcentaje:        1.23%

Dias con outliers (mostrando Return y distancia de STD):

Price                        Return  Distance_from_mean (STD)
Datetime
2026-02-06 14:30:00+00:00  7.385806                  4.548971
2026-02-26 14:30:00+00:00 -5.373192                  3.336574
2026-03-31 13:30:00+00:00  4.976976                  3.060223